source 'https://rubygems.org'

gem 'activesupport'

gem 'allure-cucumber', '~> 2.24.0'
gem 'parallel_split_test'
gem 'parallel_tests'
gem 'rake'
gem 'reek'
gem 'cucumber'
gem 'rspec'
gem 'rubocop'
gem 'ruby_raider', '~> 1.0.0'
gem 'capybara'

gem 'selenium-webdriver'
